4-javachip/front

src/app/(main)/page.tsx, src/components/pages/main/BannerSlide.tsx, src/components/pages/main/MainBannerSection.tsx, src/data/dummyDatas.ts, src/types/ResponseDataTypes.ts
ResponseDataTypes.ts 파일을 생성하여 슬라이드 배너에 대한 타입을 정의하고 더미 데이터를 만들어 적용함.
- 
- 메인 페이지 슬라이드 배너 추가
-
-
=> feat: 메인 페이지 슬라이드 배너 추가

src/app/layout.tsx
-
- layout의 div 닫힘 태그가 사라진 버그 수정
-
-
=> fix: layout의 div 닫힘 태그가 사라진 버그 수정

src/app/layout.tsx
-
- layout 페이지 children이 중복으로 입력된 버그 수정
-
-
=> fix: layout 페이지 children이 중복으로 입력된 버그 수정

src/app/product-list/page.tsx, src/components/pages/main/ProductCarousel.tsx, src/components/pages/main/ProductCarouselItem.tsx, src/components/pages/main/ProductItem.tsx, src/components/pages/product-list/ProductList.tsx, src/components/pages/product-list/ProductListItem.tsx, src/components/pages/product-list/ProductListSection.tsx, src/data/dummyDatas.ts, src/types/ResponseDataTypes.ts
-
- product list 페이지 작업
- 카테고리 타입 추가
- PrdouctItem -> ProductCarouselItem으로 다시 변경
- ProductList 페이지용 ProductItem 컴포넌트를 생성
- ProductList 페이지 퍼블리싱 작업 (style)
- 카테고리 타입, 더미 데이터 추가 
-
=> feat: product list 페이지 작업, 카테고리 타입 추가

src/app/(main)/page.tsx, src/app/layout.tsx, src/app/menu/page.tsx, src/components/layouts/Header.tsx, src/components/pages/menu/MenuCategoryList.tsx, src/components/pages/menu/MenuFooter.tsx, src/components/pages/menu/MenuHeader.tsx, src/components/ui/icons/XIcon.tsx, src/data/dummyDatas.ts, src/types/ResponseDataTypes.ts
=> feat: 메뉴 페이지 생성

src/app/product/[product_id]/page.tsx, src/components/pages/product-detail/PerchaseBar.tsx, src/components/pages/product-detail/PolicySection.tsx, src/components/pages/product-detail/PolitcyTab.tsx, src/components/pages/product-detail/ProductDescSection.tsx, src/components/pages/product-detail/ProductImg.tsx, src/components/pages/product-detail/ProductInfoSection.tsx, src/components/ui/icons/RightArrowIcon.tsx, src/components/ui/icons/ShareIcon.tsx
product별 페이지를 보여주도록 동적 라우팅 페이지 추가
PerchaseBar를 띄우고 페이지를 ProductImg, Info, Desc, Policy 섹션으로 나눔
- Closes #23
- product detail 페이지 퍼블리싱 작업
- product별 페이지를 보여주도록 동적 라우팅 페이지 추가
- PerchaseBar를 띄우고 페이지를 ProductImg, Info, Desc, Policy 섹션으로 나눔
-
=> feat: product detail 페이지 퍼블리싱 작업

src/data/dummyDatas.ts
=> fix: dummyDatas 파일 충돌 수정

src/components/pages/menu/CategoryItem.tsx, src/components/pages/menu/MenuCategoryList.tsx
- #30 
-refactor: 메뉴 카테고리 리스트 컴포넌트 분리
-
-
=> refactor: 메뉴 카테고리 리스트 컴포넌트 분리

src/components/layouts/Header.tsx, src/components/pages/menu/MenuFooter.tsx
- #32 
- 메뉴 푸터 디자인에 맞게 수정 완료 
-
-
=> menu footer 수정 및 메뉴 아이콘 링크 연결 

src/app/product/[product_id]/page.tsx, src/components/pages/product-detail/ProductDesc.tsx, src/components/pages/product-detail/ProductDescSection.tsx, src/components/pages/product-detail/ProductDetailSection.tsx, src/components/pages/product-detail/ProductImg.tsx, src/components/pages/product-detail/ProductInfo.tsx, src/data/dummyDatas.ts, src/types/ResponseDataTypes.ts
- Closes #28 
- productDetail 페이지
- ProductDetail 페이지에서 ProductDetailSection을 따로 나눔
- 더미 데이터 연결을 위해 타입을 생성하고 더미 데이터를 생성함
- 데이터 연결 작업
-
=> feat: productDetail 페이지 더미 데이터 타입을 생성하고 연결

src/components/layouts/header/Header.tsx
=>  fix: 헤더파일 import 수정

src/components/pages/productDetail/ProductImg.tsx, src/components/ui/BannerSlide.tsx
- Closes #52
- 배너 슬라이드 기능 추가
- swipe 기능 구현
- 화면 width가 늘어나도 이미지 가로 세로 너비가 정사각형으로 고정되도록 수정
-
=> feat: 배너 슬라이드 기능 추가

src/app/(shop)/products/layout.tsx, src/app/(shop)/products/page.tsx, src/components/pages/main/ProductCarousel.tsx, src/components/pages/products/CategoryCarousel.tsx, src/components/pages/products/CategoryCarouselItem.tsx, src/components/pages/products/CategoryOptionCarousel.tsx, src/components/pages/products/ProductFilterList.tsx, src/components/pages/products/ProductList.tsx, src/components/ui/ItemThumb.tsx, src/components/ui/carousels/TextCarousel.tsx, src/components/ui/carousels/TextCarouselItem.tsx, src/hooks/useCarousel.ts
- Closes #56  
- products 페이지에 카테고리 필터를 추가
- 리스트의 item ui 조정
- ProductFilterList 추가
- useCarousel을 hook으로 분리하고 CategoryCarousel 컴포넌트를 products 페이지에 추가
- TextCarousel을 생성하여 CategoryCarousel과 CategoryOptionCarousel에 사용하도록 처리
- ProductItem의 썸네일이 화면 width에 따라 반응형 조정되도록 수정
-
=> feat: products 페이지 카테고리 필터 추가, 스타일 조정

src/app/(shop)/(mainMenu)/event/page.tsx, src/app/(shop)/(mainMenu)/layout.tsx, src/app/(shop)/layout.tsx, src/components/layouts/header/Header.tsx, src/components/layouts/header/HeaderTop.tsx, src/components/layouts/header/PageNavBar.tsx, src/components/ui/buttons/LogoButton.tsx
=> Refactor : 헤더 고정 및 그림자 추가 

src/app/cart/layout.tsx, src/app/cart/page.tsx, src/components/layouts/footer/Footer.tsx, src/components/layouts/footer/FooterPolicyLinks.tsx, src/components/pages/cart/CartHeader.tsx, src/components/pages/cart/CartShippingInfo.tsx, src/data/dummyDatas.ts
- #65 
- 장바구니 header 레이아웃 분리
- header그림자 추가 및 고정 
- footer 정책 글씨체 변경 
-
-
=> refactor: 장바구니 헤더 수정 및 푸터 글씨체 변경

src/components/layouts/header/HeaderTop.tsx
- #68 
- style: 메인 헤더 위치 수정
-
-
=> style: 메인 헤더 위치 수정

src/components/pages/menu/CategoryItem.tsx, src/components/pages/menu/MenuBannerItem.tsx, src/components/pages/menu/MenuBannerList.tsx, src/components/pages/menu/MenuCategoryList.tsx, src/components/pages/menu/MenuModal.tsx
- #70 
- 모달 링크 이동 시 자동으로 닫히게 수정 
- 배너리스트 같은 css 컴포넌트 분리 
-
-
=>  style: 메뉴 모달창 링크 이동시 자동으로 닫히게 수정 , 메뉴 bannerlist 컴포넌트 분리하여 유지보수 쉽게 수정

src/components/layouts/footer/FooterPolicyLinks.tsx, src/components/layouts/footer/FooterPolicyLinksItem.tsx, src/data/dummyDatas.ts, src/types/ResponseDataTypes.ts
- #73 
-  refactor: 약관 컴포넌트 분리
-
-
=>  refactor: 약관 컴포넌트 분리

src/app/(auth)/sign-in/page.tsx, src/app/globals.css, src/components/layouts/header/PageNavBar.tsx
PageNavBar에 적용
- Closes #77
- Noto sans KR 폰트 추가
- Noto sans KR 폰트 추가
-
=> feat: Noto sans KR 폰트 추가

src/app/(shop)/products/layout.tsx, src/components/pages/products/ProductSortMenu.tsx
useSearchParams를 Suspense로 감싸도록 수정
- Closes #86
-
-
-
=> fix: 빌드 오류 해결

src/app/(shop)/product/[productId]/layout.tsx, src/app/(shop)/product/[productId]/page.tsx, src/app/(shop)/products/page.tsx, src/app/globals.css, src/components/layouts/footer/Footer.tsx, src/components/layouts/footer/FooterPolicyLinksItem.tsx, src/components/layouts/header/PageNavBar.tsx, src/components/pages/cart/CartShippingInfo.tsx, src/components/pages/menu/MenuCategoryList.tsx, src/components/pages/productDetail/ProductImg.tsx, src/components/pages/productDetail/ProductInfo.tsx, src/components/pages/productDetail/ProductNotFound.tsx, src/components/pages/products/ProductList.tsx, src/components/ui/BannerSlide.tsx
product label Icon 데이터 연동
producNotFound 컴포넌트 생성
global.css에 컬러, 폰트 추가
색상 코드들을 컬러 변수로 변경
- Closes #90
- product detail 리팩토링, global.css 색상 추가
- product label Icon 데이터 연동
- producNotFound 컴포넌트 생성
- global.css에 컬러, 폰트 추가
- 색상 코드들을 컬러 변수로 변경
-
=> feat: product detail 리팩토링, global.css 색상 추가

src/app/cart/layout.tsx, src/app/cart/page.tsx, src/components/pages/cart/CartAllCheckBar.tsx, src/components/pages/cart/CartEmpty.tsx, src/components/pages/cart/CartItem.tsx, src/components/pages/cart/CartItemList.tsx, src/components/pages/cart/CartNotice.tsx, src/components/pages/cart/CartPerchaseBar.tsx, src/components/pages/cart/CartPriceSummary.tsx, src/components/pages/cart/CartShippingInfo.tsx, src/components/pages/cart/QuantityControl.tsx, src/components/pages/cart/useCartHandlers.ts, src/components/pages/menu/MenuCategoryList.tsx, src/components/pages/order/OrderItemInfo.tsx, src/components/pages/order/OrderItemToggleList.tsx, src/components/ui/icons/MinusIcon.tsx, src/components/ui/icons/PlusIcon.tsx, src/components/ui/icons/ShowMoreIcon.tsx, src/components/ui/inputs/CheckBox.tsx, src/data/dummyDatas.ts, src/types/ResponseDataTypes.ts
- #101 
-  장바구니 글씨체 변경
- 장바구니 더미데이터 및 데이터 타입 변경 
- 장바구니 결제 할인율 연산으로 변경 
-
-
=> refactor: 장바구니 페이지 코드 리펙토링

src/components/pages/cart/CartItem.tsx, src/components/ui/inputs/CheckBox.tsx, src/data/dummyDatas.ts, src/types/ResponseDataTypes.ts
=> fix: cart build 오류 수정

src/components/pages/order/OrderCoupon.tsx
=> fix : coupon 아이콘 import 오류 수정

src/components/pages/mypage/MyPageMenu.tsx
=>  style: 패딩 수정

src/actions/auth/index.ts, src/app/auth/sign-up/page.tsx, src/components/pages/auth/signUp/MultiStepSignUp.tsx, src/components/pages/auth/signUp/SignUpEmailInput.tsx, src/components/pages/auth/signUp/SignUpPasswordInput.tsx, src/components/pages/auth/signUp/SignUpProfileInput.tsx, src/components/pages/auth/signUp/SignUpStep.tsx, src/components/pages/auth/signUp/step/SignUpStep01.tsx, src/components/pages/auth/signUp/step/SignUpStep02.tsx, src/components/ui/inputs/CustomCheckBox.tsx, src/data/dummyDatas.ts, src/schemas/signUpSchema.ts, src/types/storeDataTypes.ts
- Closes #127
- bug/feat: sign up 오류 fix/sign up step을 컴포넌트로 분리
- fix: CustomCheckBox 체크가 안되던 부분 수정
- fix: sign up 이메일 도메인 직접 입력을 선택한 후 다시 드롭다운을 선택하면 input인 상태가 유지되던 버그 수정
- feat: MultiStepSignUp 컴포넌트 분리
- feat: step을 이동해도 input 값이 value로 적용되도록 수정
email domain 값이 적용되도록 SignUpEmailInput을 수정
- feat: sign up 전화번호, 성별 input이 value로 유지되도록 수정
- feat: step1의 input(email, password)를 payload로 받아오도록 수정
formData를 사용하지 않고 state 값을 전달하는 방식으로 수정
- feat: user nickname을 not null로 변경
- fix: SignUpStep을 컴포넌트로 불러오는 방식으로 변경
-
=> bug/feat: sign up 오류 fix/sign up step을 컴포넌트로 분리

next.config.ts, src/app/api/MenuCategory/index.ts, src/components/layouts/header/HeaderTop.tsx, src/components/pages/menu/CategoryItem.tsx, src/components/pages/menu/MenuCategoryList.tsx, src/components/pages/mypage/MyPageMenu.tsx, src/data/dummyDatas.ts, src/types/ResponseDataTypes.ts
refactor: mypage 회색 바탕 h 수정
- #140 
- 메뉴 페이지 api 연결 
-
-
=>  feature: 메뉴 페이지 api 연결

src/actions/auth/index.ts, src/app/auth/terms-agreement/page.tsx, src/components/pages/auth/AuthTermsItem.tsx, src/components/pages/auth/AuthTermsList.tsx, src/components/pages/auth/signUp/MultiStepSignUp.tsx, src/data/dummyDatas.ts, src/types/ResponseDataTypes.ts
-
- sign up agreeement fetch하여 연동
- 약관 필수, 선택 체크 함수 추가
-
-
=> feat: agreement form api 연동 및 refactor

src/app/(shop)/(mainMenu)/event/page.tsx, src/app/(shop)/(mainMenu)/loading.tsx, src/app/globals.css, src/app/layout.tsx, src/components/layouts/CommonLayout.tsx, src/components/layouts/header/HeaderTop.tsx, src/components/layouts/header/PageNavBar.tsx, src/components/pages/menu/MenuSideBar.tsx, src/components/pages/menu/MenuTop.tsx
- #149 
- 페이지 너비 고정 및 반응형 적용 , 페이지 이동 시 로딩 페이지 적용 
- 페이지 로딩 확인하기 위해서 기획전 페이지에 3초 로딩 코드 만들어놓음 
-
=> feat: 전역 로딩 페이지 설정 , refactor: 전체페이지 width 변경 , 반응형 적용 

src/actions/auth/index.ts, src/components/pages/auth/signUp/MultiStepSignUp.tsx, src/components/pages/auth/signUp/step/SignUpStep03.tsx, src/components/ui/inputs/CustomCheckBox.tsx, src/data/initialDatas.ts, src/schemas/signUpSchema.ts, src/types/initialDataTypes.ts, src/types/storeDataTypes.ts
-
-
-  sign up step02에서 03으로 이동시 본인인증 메일 전송하도록 로직 추가
- 이메일 인증, 인증확인 기능 구현 및 api 연동
인증 메일 전송 및 확인 함수를 multistepsignup에서 처리하도록 구현
emailVerificationCode를 form의 storeData에 추가하여 관리하도록 수정
- 이메일 인증 유효 시간 표시 및 메일 다시 보내기 기능 추가
-
=> feat: email verification 기능 구현

src/app/api/auth/[...nextauth]/options.ts, src/app/auth/sign-in/page.tsx, src/components/pages/auth/SignInForm.tsx, src/components/pages/auth/signIn/OauthLoginButtons.tsx, src/types/ResponseDataTypes.ts
-
-
- Oauth 로그인 버튼 (카카오, 구글) 추가 및 구현
-
=> feat: Oauth 로그인 기능(프론트단) 추가

src/actions/product-service/index.ts, src/app/layout.tsx, src/types/ResponseDataTypes.ts
=> chore: productOptionType 추가

src/app/auth/sign-up/page.tsx, src/components/pages/auth/AuthTermsList.tsx, src/components/pages/auth/signUp/MultiStepSignUp.tsx, src/components/pages/auth/signUp/SignUpComplete.tsx, src/components/pages/auth/signUp/SignUpEmailInput.tsx, src/components/pages/auth/signUp/SignUpEmailVerify.tsx, src/components/pages/auth/signUp/TermsAgreements.tsx, src/components/pages/auth/signUp/step/SignUpStep02.tsx, src/components/pages/auth/signUp/step/SignUpStep03.tsx, src/components/ui/ErrorAlertModal.tsx, src/components/ui/buttons/ConfirmNextButton.tsx.tsx, src/components/ui/loader.tsx, src/data/initialDatas.ts, src/schemas/signUpSchema.ts, src/types/storeDataTypes.ts
=> feat: sign up 스텝 변경 및 인증 예외 처리/리팩터

src/actions/auth/index.ts, src/app/api/auth/[...nextauth]/options.ts, src/components/pages/auth/SignInForm.tsx, src/components/pages/auth/signUp/MultiStepSignUp.tsx, src/components/pages/mypage/LogOutButton.tsx, src/components/ui/ErrorAlertModal.tsx, src/components/ui/buttons/CommonButton.tsx, src/schemas/signInSchema.ts, src/types/ResponseDataTypes.ts, src/types/storeDataTypes.ts
-
- sign in input 유효성 검사 추가
- 로그인 오류시 모달 창을 띄우도록 수정
- log out 시 session을 가져오지 못하던 오류 해결
-
-
=> refactor: auth refactor

src/actions/shipping-address-service/index.ts
=>  fix: import 오류 해결

src/actions/shipping-address-service/index.ts, src/components/pages/ShippingAddress/ShippingAddressList.tsx
- #183 
- 배송지 목록에서 기본배송지가 맨위에 나오게 수정 
-
-
=> refactor: 배송지 목록 수정 

src/actions/shipping-address-service/index.ts, src/app/layout.tsx, src/components/pages/ShippingAddress/ShippingAddressList.tsx, src/components/ui/icons/DefaultIcon.tsx
-
- 배송지 api 헤더에 넘겨주는 useruuid 값 ->token 으로 변경 
-
-
=> refacotr: 배송지 api 헤더에 useruuid ->  token 으로 변경 

src/actions/product-service/index.ts, src/app/(shop)/(main)/mypage/page.tsx, src/app/(shop)/products/page.tsx, src/app/api/auth/[...nextauth]/options.ts, src/app/layout.tsx, src/components/pages/auth/signIn/OauthLoginButtons.tsx, src/components/pages/event/EventSection.tsx, src/components/pages/products/ProductList.tsx, src/components/ui/productItem/ProductItem.tsx, src/components/ui/productItem/ProductScrollObserver.tsx, src/components/ui/skeletons/ProductItemSkeleton.tsx, src/types/ProductResponseDataTypes.ts
=> feat: products infinite scroll

next.config.ts, package.json, pnpm-lock.yaml, src/actions/agreement-service/index.ts, src/actions/shipping-address-service/index.ts, src/app/(shipping)/shipping-addresses/page.tsx, src/app/shippingaddress-agreement/layout.tsx, src/app/shippingaddress-agreement/page.tsx, src/components/layouts/footer/Footer.tsx, src/components/pages/ShippingAddress/ShippingAddressList.tsx, src/components/pages/menu/CategoryItem.tsx, src/components/pages/mypage/MyPageMenu.tsx, src/components/pages/shippingaddress-agreement/Description.tsx, src/components/pages/shippingaddress-agreement/SAHeader.tsx, src/components/pages/shippingaddress-agreement/SATTop.tsx, src/components/ui/label.tsx, src/components/ui/switch.tsx, src/components/ui/texts/TextTitleH1.tsx, src/types/RequestDataTypes.ts, src/types/ResponseDataTypes.ts
- #186 
- 배송지 약관 동의 페이지 퍼블리싱 
- 배송지 index.ts 파일 오류 해결 
- 
-  shadcn 에서 switch, label install
=> feat: 배송지 약관동의 index.ts 파일 생성 및 퍼블리싱 

src/components/pages/ShippingAddress/AddShippingAddress.tsx, src/components/pages/ShippingAddress/ShippingAddressList.tsx, src/components/pages/shippingaddress-agreement/ShippingAddressAgreementHeader.tsx, src/components/ui/ConfirmModal.tsx, src/components/ui/alert-dialog.tsx
- #196 
- 배송지 이용약관 true-> false 로 상태 변경시 바로 상태 변경 되지 않고 비동의 확인 모달로 1차 확인 후 상태변경 
- 배송지 삭제 시 바로 삭제되지 않고 삭제 확인 후 배송지 삭제 
-
-
=> feat : 배송지 이용약관 상태 변경 및 배송지 삭제 시 확인 모달 추가 

src/actions/cart-service/index.ts, src/actions/product-service/index.ts, src/app/cart/page.tsx, src/components/pages/cart/CartItemList.tsx, src/components/pages/cart/QuantityControl.tsx, src/components/ui/CartItem/CartItem.tsx, src/components/ui/CartItem/CartThumbnail.tsx, src/components/ui/inputs/CheckBox.tsx, src/types/CartDataType.ts, src/types/ProductResponseDataTypes.ts
=> [fix] cart

next.config.ts, src/actions/auth/index.ts, src/app/(shop)/(main)/event/page.tsx, src/app/auth/sign-up/page.tsx, src/components/pages/auth/signUp/MultiStepSignUp.tsx, src/components/pages/auth/signUp/SignUpEmailVerify.tsx, src/components/pages/mypage/LogOutButton.tsx, src/components/ui/ErrorAlertModal.tsx, src/data/dummyDatas.ts
-
-
- fetching 함수를 throw 방식이 아닌 success 여부와 message를 반환하게 하고, try catch를 fetching 함수에 넣도록 수정하여 에러 예외 처리 오류 수정
An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.
-
=> fix: auth 페이지 배포 시 에러 수정

src/actions/auth/index.ts, src/actions/product-service/index.ts, src/components/pages/ShippingAddress/AddShippingAddress.tsx, src/components/ui/CartItem/CartThumbnail.tsx, src/components/ui/inputs/CheckBox.tsx, src/data/dummyDatas.ts, src/hooks/useInfiniteProductList.tsx
=>  fix : 빌드 오류 수정

src/app/cart/page.tsx, src/app/order/layout.tsx, src/components/layouts/header/HeaderTop.tsx, src/components/pages/cart/CartAllCheck.tsx, src/components/pages/cart/CartItemList.tsx, src/components/pages/cart/CartNotice.tsx, src/components/pages/cart/CartPriceSummary.tsx, src/components/pages/cart/CartPurchaseBar.tsx, src/components/pages/menu/MenuSideBar.tsx, src/components/ui/CartItem/CartItem.tsx, src/components/ui/CartItem/CartThumbnail.tsx, src/components/ui/buttons/CartButton.tsx, src/components/ui/buttons/DeleteButton.tsx, src/hooks/useInfiniteProductList.tsx, src/types/CartDataType.ts
- #228 
- 헤더 장바구니 뱃지로 장바구니에 있는 상품 수 표시 
- 장바구니에 구매하기 바에 장바구니 갯수 및 구매가격 표시
-
-
=> feat: 장바구니 상품 갯수 헤더에 표시 및 구매 바에 표시

src/actions/auth/index.ts, src/app/api/auth/[...nextauth]/options.ts, src/app/auth/oauth-sign-up/page.tsx, src/components/pages/auth/signIn/OauthLoginButtons.tsx, src/hooks/useInfiniteProductList.tsx, src/types/RequestDataTypes.ts, src/types/storeDataTypes.ts
=> feat: oauth 로그인 함수 추가 및 oauth_cookie를 oauth sign in 시 받아오도록 설정

src/actions/auth/index.ts, src/app/api/auth/[...nextauth]/options.ts, src/app/auth/oauth-sign-up/page.tsx, src/app/cart/page.tsx, src/app/order/layout.tsx, src/components/layouts/header/HeaderTop.tsx, src/components/pages/auth/signIn/OauthLoginButtons.tsx, src/components/pages/cart/CartAllCheck.tsx, src/components/pages/cart/CartItemList.tsx, src/components/pages/cart/CartNotice.tsx, src/components/pages/cart/CartPriceSummary.tsx, src/components/pages/cart/CartPurchaseBar.tsx, src/components/pages/menu/MenuSideBar.tsx, src/components/ui/CartItem/CartItem.tsx, src/components/ui/CartItem/CartThumbnail.tsx, src/components/ui/buttons/CartButton.tsx, src/components/ui/buttons/DeleteButton.tsx, src/hooks/useInfiniteProductList.tsx, src/types/CartDataType.ts, src/types/RequestDataTypes.ts, src/types/storeDataTypes.ts
=> merge dev to main

src/app/api/auth/[...nextauth]/options.ts
=> feat: oauth 설정

package.json, src/actions/order-service/index.ts, src/actions/shipping-address-service/index.ts, src/app/cart/page.tsx, src/app/order/page.tsx, src/components/pages/cart/CartItemList.tsx, src/components/pages/order/OrderItem.tsx, src/components/pages/order/OrderItemSummary.tsx, src/components/pages/order/OrderItemToggleList.tsx, src/components/pages/order/OrderList.tsx, src/components/pages/order/OrderPriceSummary.tsx, src/components/pages/order/OrderShippingInfo.tsx, src/components/ui/CartItem/CartItem.tsx, src/components/ui/CartItem/ItemName.tsx, src/components/ui/CartSelectAddressList/CartSelectAddressList.tsx, src/components/ui/orderItem/OrderThumb.tsx, src/types/OrderDataType.ts
- #230 
- 주문 페이지 api 연동 및 배송지 변경 기능 추가 
-
-
=>  feat: 주문 페이지 api 연동 및 배송지 변경 기능 추가

package.json, src/actions/auth/index.ts, src/actions/cart-service/index.ts, src/actions/product-service/index.ts, src/app/api/auth/[...nextauth]/options.ts, src/app/auth/oauth-sign-up/page.tsx, src/components/pages/auth/SignInForm.tsx, src/components/pages/menu/CategoryItem.tsx, src/components/pages/menu/MenuCategoryList.tsx, src/components/pages/menu/MenuTop.tsx, src/components/pages/productDetail/ProductDesc.tsx, src/components/pages/productDetail/ProductDetailSection.tsx, src/components/pages/productDetail/PurchaseBar/PurchaseBar.tsx, src/components/pages/productDetail/PurchaseBar/PurchaseBarBottomContent.tsx, src/components/pages/productDetail/PurchaseBar/PurchaseBottomSheet.tsx, src/components/pages/productDetail/PurchaseBar/PurchaseItem.tsx, src/components/pages/productDetail/PurchaseBar/PurchaseQuantityControl.tsx, src/components/ui/accordions/AccordionSelector.tsx, src/components/ui/alert-dialog.tsx, src/components/ui/buttons/MenuButton.tsx, src/components/ui/dialogs/AlertModal.tsx, src/types/CartDataType.ts, src/types/storeDataTypes.ts
-
- product detail purchaseBar 옵션 선택 처리 (컬러와 사이즈 옵션 유무에 따라 달라지는 분기 처리) 기능 추가
- 갯수 조절 기능 추가
- purchaseBar 스타일 조정
- alertModal 스타일 조정
- menuCategory, product detail description HTML style 소폭 조정
- purchaseBar 장바구니 추가 기능 및 예외 처리
-
-
=> feat: 제품 상세 페이지 옵션 선택 및 장바구니 추가 기능 

package-lock.json, package.json, src/actions/payments-service/index.ts, src/app/layout.tsx, src/app/order/page.tsx, src/app/payment/fail/page.tsx, src/app/payment/success/page.tsx, src/components/pages/order/OrderItem.tsx, src/components/pages/order/OrderList.tsx, src/components/pages/order/OrderPriceSummary.tsx, src/components/pages/order/OrderPurchaseBar.tsx, src/context/OrderItemContext.tsx, src/hooks/usePriceSummary.ts, src/types/PaymentDataType.ts
=> feat: 결제 페이지 생성 및 api 연동 

src/actions/event-service/index.ts
=> fix: event action에서 BASE_API_URL을 상수로 지정하도록 수정

src/actions/event-service/index.ts
=> Fix: build fix

src/actions/order-service/index.ts, src/actions/payments-service/index.ts, src/app/(orderpayment)/layout.tsx, src/app/(orderpayment)/order/layout.tsx, src/app/(orderpayment)/payment/success/page.tsx, src/app/(shipping)/shipping-add/page.tsx, src/components/pages/shippingaddress-agreement/Description.tsx, src/components/ui/payment/OrderItemThumb.tsx, src/context/PaymentSuccessContext.tsx, src/types/OrderDataType.ts, src/types/PaymentDataType.ts
=> feat: 결제 성공 페이지 퍼블리싱 

src/actions/order-service/index.ts, src/actions/payments-service/index.ts, src/app/(orderpayment)/order/layout.tsx, src/app/(orderpayment)/payment/success/page.tsx, src/app/order-list/page.tsx, src/components/pages/payment-success/paymentPurchasebar.tsx
=>  refactor: 결제 성공 페이지 커스텀

src/actions/wishlist-service/index.ts, src/app/wishlist/layout.tsx, src/app/wishlist/page.tsx, src/components/pages/mypage/MyPageMenu.tsx, src/components/pages/productDetail/ProductDetailSection.tsx, src/components/pages/productDetail/ProductInfo.tsx, src/components/pages/wishlist/WishListHeader.tsx, src/components/ui/buttons/WishButton.tsx, src/types/ProductResponseDataTypes.ts
-
-feat: 상품 상세페이지 찜 기능 추가 및 찜 목록페이지 api 연동 
-feat: 상품 상세페이지 찜 기능 추가 및 찜 목록페이지 api 연동 
-
=> feat: 상품 상세페이지 찜 기능 추가 및 찜 목록페이지 api 연동 

src/components/pages/menu/MenuSideBar.tsx, src/components/pages/order/OrderPurchaseBar.tsx
=> fix:메뉴 사이드바 스크롤 안되는 현상 수정

src/app/(orderpayment)/payment/fail/page.tsx, src/app/(orderpayment)/payment/success/page.tsx, src/components/pages/order/OrderItem.tsx, src/components/pages/payment-fail/PaymentFailButtonBar.tsx, src/components/pages/payment-success/ConfirmPaymentModalWrapper.tsx, src/components/pages/payment-success/PaymentAddressInfo.tsx, src/types/OrderDataType.ts
=> refactor: 결제 성공 실패 페이지 수정 및 퍼블리싱 

src/app/api/auth/[...nextauth]/options.ts, src/app/auth/oauth-sign-up/page.tsx, src/components/pages/auth/signIn/OauthLoginButtons.tsx, src/components/pages/auth/signUp/MultiStepSignUp.tsx, src/components/pages/productDetail/Review/ProductReviewItem.tsx, src/components/ui/products/ProductItem.tsx, src/schemas/oAuthSignUpSchema.ts
=> feat: oauth sign up form 추가

src/app/(shipping)/shipping-add/page.tsx, src/components/pages/ShippingAddress/AddShippingAddress.tsx, src/components/pages/ShippingAddress/EmptyAddress.tsx, src/components/pages/ShippingAddress/ShippingAddressForm.tsx, src/components/pages/order/OrderAddressEmptySection.tsx, src/components/pages/order/OrderPurchaseBar.tsx
=>  fix:배송지 약관 오류 수정

src/app/(orderpayment)/order/page.tsx, src/components/pages/order/OrderAddressEmptySection.tsx, src/components/pages/order/OrderProductList.tsx, src/components/pages/order/OrderShippingInfo.tsx
=> refactor: 배송지 empty섹션 및 주문 명 변경 

src/actions/product-service/index.ts, src/app/(orderpayment)/order/page.tsx, src/components/pages/cart/CartItemList.tsx, src/components/pages/order/OrderItem.tsx, src/components/pages/order/OrderProductList.tsx, src/components/ui/CartItem/CartItem.tsx, src/components/ui/CartItem/CartThumbnail.tsx, src/types/OrderDataType.ts
=>  fix: 장바구니에 옵션명 추가 , 주문 페이지도 동일하게 수정

src/actions/cart-service/index.ts, src/actions/payments-service/index.ts
=>  fix:결제 성공 시 장바구니에 상품 삭제

src/actions/cart-service/index.ts, src/actions/payments-service/index.ts, src/components/layouts/header/Header.tsx, src/components/layouts/header/HeaderTop.tsx, src/components/pages/menu/MenuSideBar.tsx, src/components/ui/buttons/CartButton.tsx, src/components/ui/buttons/MenuButton.tsx, src/components/ui/buttons/SearchButton.tsx, src/components/ui/buttons/UserAuthButton.tsx
=> fix:상품 추가 시 헤더에 있는 장바구니 상품 수 새로고침 없이 update 가능 

src/actions/cart-service/index.ts, src/actions/payments-service/index.ts, src/components/layouts/header/Header.tsx, src/components/layouts/header/HeaderTop.tsx, src/components/pages/menu/MenuSideBar.tsx, src/components/pages/order/OrderItem.tsx, src/components/ui/buttons/CartButton.tsx, src/components/ui/buttons/MenuButton.tsx, src/components/ui/buttons/SearchButton.tsx, src/components/ui/buttons/UserAuthButton.tsx
=> fix:  오류 수정 

src/app/(shipping)/addshipping/page.tsx, src/components/pages/ShippingAddress/ShippingAddressForm.tsx, src/components/ui/inputs/AddressInput.tsx
=> fix : 배송지 오류 수정 

src/app/(review)/addReview/[orderDetailUuid]/page.tsx
=> fix: 리뷰 작성 빌드시 에러 해결

src/actions/order-service/index.ts, src/app/(orderpayment)/layout.tsx, src/app/(shipping)/shippingaddresses/[shippingAddressUuid]/page.tsx, src/components/layouts/CommonLayout.tsx, src/components/pages/ShippingAddress/AddShippingAddress.tsx, src/components/pages/ShippingAddress/ShippingAddressList.tsx, src/components/pages/mypage/OrderDeliveryStatus.tsx, src/components/pages/shippingaddress-agreement/ShippingAddressAgreementHeader.tsx, src/components/ui/CartSelectAddressList/CartSelectAddressList.tsx, src/types/RequestDataTypes.ts
=> fix: 에러 수정 및 결제하기 header변경 

src/app/order-list/layout.tsx, src/components/pages/payment-success/PaymentInfo.tsx
=> refactor: 주문 상세내역 헤더 변경 및 paymentSuccess페이지 pb 추가

src/app/order-list/layout.tsx, src/components/pages/orderlist/OrderDetailList.tsx, src/components/pages/orderlist/OrderList.tsx, src/components/pages/orderlist/OrderPaymentInfo.tsx, src/components/pages/payment-success/PaymentInfo.tsx
=> refactor: 결제 성공 페이지 pb 수정 

next.config.ts, src/actions/auth/index.ts, src/app/api/auth/[...nextauth]/options.ts, src/app/auth/qr-sign-in/page.tsx, src/app/error.tsx, src/app/layout.tsx, src/app/not-found.tsx, src/components/pages/auth/signIn/QrSignInTrigger.tsx
=> feat: 404 error page 및 qr 로그인 구현
